services:
  db:
    image: postgres:latest
    container_name: inflearn_clone_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prismapass
      POSTGRES_DB: inflearn_clone
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:w
  postgres_data: